const quotes = [
    "Believe in yourself!",
    "Your only limit is your mind.",
    "Dream big, work hard!",
    "Success is a journey, not a destination.",
    "Keep going, you're closer than you think.",
    "Doubt kills more dreams than failure ever will.",
    "You are capable of amazing things.",
    "Push yourself, because no one else is going to do it for you.",
    "Failure is the opportunity to begin again, more intelligently.",
    "Your vibe attracts your tribe.",
    "Don’t stop until you’re proud.",
    "Every expert was once a beginner.",
    "You are stronger than you think.",
    "If you believe in yourself, anything is possible.",
    "Hardships often prepare ordinary people for an extraordinary destiny.",
    "Make today so awesome that yesterday gets jealous.",
    "It’s never too late to be what you might have been.",
    "You didn’t come this far to only come this far.",
    "The harder you work for something, the greater you’ll feel when you achieve it.",
    "The best way to predict the future is to create it.",
    "Do something today that your future self will thank you for.",
    "Success doesn’t just find you, you have to go out and get it.",
    "Sometimes later becomes never. Do it now.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "Your dreams don’t work unless you do.",
    "Difficult roads often lead to beautiful destinations.",
    "It always seems impossible until it’s done.",
    "You get what you focus on, so focus on what you want.",
    "If it doesn’t challenge you, it won’t change you.",
    "Do what you love, love what you do.",
    "You don’t have to be great to start, but you have to start to be great.",
    "Opportunities don’t happen, you create them.",
    "Don’t wait for opportunity. Create it.",
    "Work hard in silence, let success make the noise.",
    "Stay patient and trust your journey.",
    "A little progress each day adds up to big results.",
    "Your attitude determines your direction.",
    "Dare to dream, dare to do.",
    "Everything you need to accomplish your goals is already inside you.",
    "Your time is now.",
    "Go the extra mile, it’s never crowded.",
    "Rise up, start fresh, see the bright opportunity in each day.",
    "You are one decision away from a completely different life.",
    "Start where you are. Use what you have. Do what you can.",
    "Consistency is what transforms average into excellence.",
    "You will never always be motivated, so you must learn to be disciplined.",
    "Small steps in the right direction can turn out to be the biggest step of your life.",
    "Dream big, start small, act now.",
    "If you want something you've never had, you must be willing to do something you've never done.",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",
    "No matter how slow you go, you are still lapping everyone on the couch.",
    "Don’t be afraid to give up the good to go for the great.",
    "Act as if what you do makes a difference. It does.",
    "Strive for progress, not perfection.",
    "The best revenge is massive success.",
    "Doubt is the enemy of progress.",
    "Your speed doesn’t matter, forward is forward.",
    "Don't let yesterday take up too much of today.",
    "The only way to do great work is to love what you do.",
    "Stop doubting yourself, work hard, and make it happen.",
    "Stay focused and never give up.",
    "Every day may not be good, but there’s something good in every day.",
    "Dream it. Believe it. Build it.",
    "Go confidently in the direction of your dreams.",
    "Wake up with determination, go to bed with satisfaction.",
    "Take the risk or lose the chance.",
    "Your greatness is not what you have, but what you give.",
    "If the plan doesn’t work, change the plan, not the goal.",
    "Difficulties in life are intended to make us better, not bitter.",
    "It takes courage to grow up and become who you really are.",
    "Nothing worth having comes easy.",
    "Life is tough, but so are you.",
    "The difference between a successful person and others is not a lack of strength, but a lack of will.",
    "Great things never come from comfort zones.",
    "Your passion is waiting for your courage to catch up.",
    "Hustle until your haters ask if you’re hiring.",
    "Don’t tell people your plans, show them your results.",
    "The comeback is always stronger than the setback.",
    "Whatever you do, do it with all your heart.",
    "Work until your idols become your rivals.",
    "Learn from yesterday, live for today, hope for tomorrow.",
    "Make it happen. Shock everyone.",
    "Turn your obstacles into opportunities.",
    "Don’t let the fear of losing be greater than the excitement of winning.",
    "A goal properly set is halfway reached.",
    "Be a warrior, not a worrier.",
    "Live less out of habit and more out of intent.",
    "The best view comes after the hardest climb.",
    "Success is not in what you have, but who you are.",
    "Do more of what makes you happy.",
    "Be the energy you want to attract.",
    "Start each day with a grateful heart.",
    "Opportunities multiply as they are seized.",
    "It's not whether you get knocked down, it's whether you get up.",
    "Live your dreams, don’t dream your life.",
    "Think big. Trust yourself. Make it happen.",
    "You have within you right now, everything you need to deal with whatever the world throws at you.",
    "Winners focus on winning. Losers focus on winners.",
    "The moment you want to quit is the moment you need to keep pushing.",
    "Success is getting what you want. Happiness is wanting what you get.",
    "The road to success is always under construction.",
    "Stay hungry. Stay foolish.",
    "You are the artist of your own life. Don’t hand the paintbrush to anyone else.",
    "If you want to fly, give up everything that weighs you down.",
    "Happiness depends upon ourselves.",
    "A river cuts through rock, not because of its power, but because of its persistence.",
    "Turn your wounds into wisdom.",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently.",
    "The key to success is to start before you are ready.",
    "A year from now you may wish you had started today.",
    "Believe you can and you’re halfway there."
];

function generateQuote() {
    const quoteElement = document.getElementById("quote-text");
    const randomIndex = Math.floor(Math.random() * quotes.length);
    quoteElement.textContent = quotes[randomIndex];
}

document.addEventListener("DOMContentLoaded", generateQuote);
